elt_platform:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: elt_platform-admin
      password: elt_platform-admin
      port: 5432
      dbname: elt_platform
      schema: public
      threads: 1
