FROM apache/airflow:2.7.3-python3.11

USER root
RUN apt-get update && apt-get install -y default-jdk && apt-get clean
ENV JAVA_HOME=/usr/lib/jvm/default-java

USER airflow
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt
RUN mkdir -p /opt/airflow/logs && chown -R 50000:0 /opt/airflow/logs
