FROM apache/airflow:2.7.3-python3.11

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt
RUN mkdir -p /opt/airflow/logs && chown -R 50000:0 /opt/airflow/logs
